spring.application.name=payment-service
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_service_db_salon_booking
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8085

razorpay.api.key="rzp_test_us_SP5Kr0YDhq4l4x"
razorpay.api.secret="662aR6SMiyni7YIhdwYlt8RW"

stripe.api.key="pk_test_51T90Y8GVJ3P1R0kJJg32ywoZNlLEGfk3e2JB7B2P5aVy0e9KmBZBOK5VUJlvwABem2rkXKhDYgouHeBXgzDeHWAJ00oLXXq8Ux"

#sk_test_51T90Y8GVJ3P1R0kJGTlcoy7Szt81k9Y6fkbCNEgnPU8y7XjA6j9bayTZBoMA2wlRDC80NkS5hfLk0uZrSiPaw76N00EuEA4M14
stripe.api.secret=${STRIPE_SECRET_KEY} 