spring.application.name=payment-service
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_service_db_salon_booking
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8085

razorpay.api.key="rzp_test_us_SP5Kr0YDhq4l4x"
razorpay.api.secret="662aR6SMiyni7YIhdwYlt8RW"

stripe.api.key=${STRIPE_API_KEY}

stripe.api.secret=${STRIPE_SECRET_KEY} 