services:

  user_db_salon_booking:
    image: postgres:16
    container_name: user_db_salon_booking
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - user-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_db_salon_booking
    networks:
      - vmt1609

  booking_service_db_salon_booking:
    image: postgres:16
    container_name: booking_service_db_salon_booking
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: booking_service_db_salon_booking
    volumes:
      - booking-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - vmt1609

  category_db_salon_booking:
    image: postgres:16
    container_name: category_db_salon_booking
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: category_db_salon_booking
    volumes:
      - category-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    networks:
      - vmt1609

  payment_service_db_salon_booking:
    image: postgres:16
    container_name: payment_service_db_salon_booking
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: payment_service_db_salon_booking
    volumes:
      - payment-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    networks:
      - vmt1609

  salon_db_salon_booking:
    image: postgres:16
    container_name: salon_db_salon_booking
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: salon_db_salon_booking
    volumes:
      - salon-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    networks:
      - vmt1609

  service_offer_db_salon_booking:
    image: postgres:16
    container_name: service_offer_db_salon_booking
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: service_offer_db_salon_booking
    volumes:
      - service-offer-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    networks:
      - vmt1609

  notification_db_salon_booking:
    image: postgres:16
    container_name: notification_db_salon_booking
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: notification_salon_booking
    volumes:
      - notification-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    networks:
      - vmt1609

  review_db_salon_booking:
    image: postgres:16
    container_name: review_db_salon_booking
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: review_db_salon_booking
    volumes:
      - review-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    networks:
      - vmt1609

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - vmt1609

  eurekaserver:
    image: "vmt1609/salon-eureka-server:v1"
    ports:
      - "9999:9999"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:9999/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    container_name: eurekaserver

    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - vmt1609


  user:
    image: "vmt1609/salon-user-service:v1"
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: user
    depends_on:
      user_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "user-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://user_db_salon_booking:5432/user_db_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609


  booking:
    image: "vmt1609/salon-booking-service:v1"
    ports:
      - "8084:8084"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: booking
    depends_on:
      booking_service_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "booking-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://booking_service_db_salon_booking:5432/booking_service_db_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

  category:
    image: "vmt1609/salon-category-service:v1"
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: category
    depends_on:
      category_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "category-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://category_db_salon_booking:5432/category_db_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

  payment:
    image: "vmt1609/salon-payment-service:v1"
    ports:
      - "8085:8085"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: payment
    depends_on:
      payment_service_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "payment-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://payment_service_db_salon_booking:5432/payment_service_db_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

  salon:
    image: "vmt1609/salon-service:v1"
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: salon
    depends_on:
      salon_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "salon-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://salon_db_salon_booking:5432/salon_db_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

  service_offering:
    image: "vmt1609/salon-service-offering:v1"
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: service_offering
    depends_on:
      service_offer_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "service-offering"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://service_offer_db_salon_booking:5432/service_offer_db_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

  notification:
    image: "vmt1609/salon-notification-service:v1"
    ports:
      - "8086:8086"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8086/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: notification
    depends_on:
      notification_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "notification-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://notification_db_salon_booking:5432/notification_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

  review:
    image: "vmt1609/salon-review-service:v1"
    ports:
      - "8087:8087"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8087/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: review
    depends_on:
      review_db_salon_booking:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "review"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://review_db_salon_booking:5432/review_db_salon_booking"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

  gatewayservice:
    image: "vmt1609/salon-gateway-service:v1"
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    container_name: gatewayservice
    environment:
      SPRING_APPLICATION_NAME: "gateway-service"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9999/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vmt1609

networks:
  vmt1609:
    driver: "bridge"

volumes:
  user-data:
  booking-data:
  category-data:
  payment-data:
  salon-data:
  service-offer-data:
  notification-data:
  review-data:
  rabbitmq-data:
